### ISSUE TITLE
Proposition project

### ISSUE THREAD

**Issue by gbasset** [king04aman/All-In-One-Javascript-Projects#3]
### Project Suggestion Title
temperator converter

### Description
_I can code a converter from degrees to celsius.

### Implementation Ideas
_I'm proposing a classic html interface, the first of which will include a switch for choosing the type of conversion.
For example, celsius to fahrenheit or fahrenheit to celsius. 
Below this is an input to indicate the temperature to be converted.
And finally, a button to send the data.
There will be error handling with associated messages.

**Comment by king04aman** [comment]
Hi @gbasset ,

Thank you for your project suggestion on the temperature converter! Assigned to you, Happy Coding 🥳

**Comment by gbasset** [comment]
Hi @king04aman , thank you :) !

**Comment by gbasset** [comment]
Hello i send you the code in pull request :)

**Comment by king04aman** [comment]
Thanks for your contribution @gbasset! Merged!!

**Comment by gbasset** [comment]
Thank you , but why my work does not count for hacktoberfest ?
You could not add label ? 
I have other's ideas for the project, i create a new issue.

**Comment by king04aman** [comment]
> Thank you , but why my work does not count for hacktoberfest ? You could not add label ? I have other's ideas for the project, i create a new issue.

Your PR has already been merged with `hacktoberfest` label. It will reflect your dashboard soon!
