### ISSUE TITLE
Build a Simpsons Quotes Web Application using Public API

### ISSUE THREAD

**Issue by gbasset** [king04aman/All-In-One-Javascript-Projects#7]
### Project Suggestion Title
Simpsons Quotes

### Description
The idea for this project is to develop a web application using HTML, CSS, and JavaScript that fetches and displays quotes from characters in The Simpsons TV show. This will be done by integrating a public API that provides quotes related to the show.
### Implementation Ideas
Use a public API that provides random or specific quotes from The Simpsons characters. The API will be fetched using JavaScript (e.g., fetch or axios).
A button to fetch a new quote.
An area where the quote and the character's name will be displayed.
Fetch quotes from the API when the button is clicked.
Display the fetched quote dynamically on the page without reloading.
Implement error handling for failed API calls (e.g., display a friendly error message).

This project will provide a good introduction to working with public APIs and developing dynamic content using JavaScript.

**Comment by king04aman** [comment]
Assigned! Good Luck 🥳

**Comment by gbasset** [comment]
Thank you,  i make pullrequest :)

**Comment by gbasset** [comment]
Hello! Could you please add the Hacktoberfest labels to this PR? I'm not sure if it's currently counting towards Hacktoberfest or if it's within the required timeline. Thanks!
